//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceCalculatorSOAPClient.ServiceReferenceCalculator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalculator.IServiceDistanceCalculator")]
    public interface IServiceDistanceCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDistanceCalculator/CalculateDistance", ReplyAction="http://tempuri.org/IServiceDistanceCalculator/CalculateDistanceResponse")]
        double CalculateDistance(int startX, int startY, int endX, int endY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDistanceCalculator/CalculateDistance", ReplyAction="http://tempuri.org/IServiceDistanceCalculator/CalculateDistanceResponse")]
        System.Threading.Tasks.Task<double> CalculateDistanceAsync(int startX, int startY, int endX, int endY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDistanceCalculatorChannel : global::DistanceCalculatorSOAPClient.ServiceReferenceCalculator.IServiceDistanceCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDistanceCalculatorClient : System.ServiceModel.ClientBase<global::DistanceCalculatorSOAPClient.ServiceReferenceCalculator.IServiceDistanceCalculator>, global::DistanceCalculatorSOAPClient.ServiceReferenceCalculator.IServiceDistanceCalculator {
        
        public ServiceDistanceCalculatorClient() {
        }
        
        public ServiceDistanceCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDistanceCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDistanceCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDistanceCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateDistance(int startX, int startY, int endX, int endY) {
            return base.Channel.CalculateDistance(startX, startY, endX, endY);
        }
        
        public System.Threading.Tasks.Task<double> CalculateDistanceAsync(int startX, int startY, int endX, int endY) {
            return base.Channel.CalculateDistanceAsync(startX, startY, endX, endY);
        }
    }
}
